services:
  - type: web
    name: emlak-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: emlak-database
          property: connectionString
      - key: JWT_KEY
        generateValue: true
      - key: JWT_ISSUER
        value: emlak-api.render.com
      - key: JWT_AUDIENCE
        value: emlak-api.render.com
      - key: JWT_EXPIRES_IN_MINUTES
        value: 60

databases:
  - name: emlak-database
    databaseName: emlak_db
    user: emlak_user 